### ISSUE TITLE
Commissioner ID

### ISSUE THREAD

**Issue by chf2** [balloosnafoo/no-kicker#2]
Can leagues have multiple commissioners? If not (I thought they didn't but could totally be wrong), it might make more sense to just have a commissioner_id column in your league table rather than have it's own separate table.

**Comment by balloosnafoo** [comment]
You're right, there's only one, I think I got confused because a user can
be commissioner of multiple leagues. Thanks for the note.

**Comment by balloosnafoo** [comment]
Commissionerships removed from schema.md
